// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	structs "github.com/ZeroXKiritsu/urlshortener/structs"
	gomock "github.com/golang/mock/gomock"
)

// MockShortURL is a mock of ShortURL interface.
type MockShortURL struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLMockRecorder
}

// MockShortURLMockRecorder is the mock recorder for MockShortURL.
type MockShortURLMockRecorder struct {
	mock *MockShortURL
}

// NewMockShortURL creates a new mock instance.
func NewMockShortURL(ctrl *gomock.Controller) *MockShortURL {
	mock := &MockShortURL{ctrl: ctrl}
	mock.recorder = &MockShortURLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURL) EXPECT() *MockShortURLMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShortURL) Create(url structs.Requests) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShortURLMockRecorder) Create(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShortURL)(nil).Create), url)
}

// GenerateShortURL mocks base method.
func (m *MockShortURL) GenerateShortURL() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortURL")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateShortURL indicates an expected call of GenerateShortURL.
func (mr *MockShortURLMockRecorder) GenerateShortURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortURL", reflect.TypeOf((*MockShortURL)(nil).GenerateShortURL))
}

// GetOriginal mocks base method.
func (m *MockShortURL) GetOriginal(shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginal", shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginal indicates an expected call of GetOriginal.
func (mr *MockShortURLMockRecorder) GetOriginal(shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginal", reflect.TypeOf((*MockShortURL)(nil).GetOriginal), shortURL)
}
